### ISSUE TITLE
bug: uninitialized constant RSpec::Support::Differ

### ISSUE THREAD

**Issue by brendonmartino** [chefspec/chefspec#766]
We're having a problem with running Chefspec on a large deployment on our Jenkins Server.
Executing chefspec for the deployment works fine for just about everything:

`chef exec rspec spec -r ./spec/spec_helper.rb`

However, there is one resource in particular that is giving us trouble:

```
Finished in 4 minutes 10 seconds (files took 3.4 seconds to load)
536 examples, 0 failures

ChefSpec Coverage report generated...
  Total Resources:   157
  Touched Resources: 156
  Touch Coverage:    99.36%

Untouched Resources:
  group[docker]                      man/recipes/install_docker.rb:130
```

The resource on line 130 in question is:

```
# add dd-agent to docker group if datadog agent is present
group 'docker' do
  action :modify
  members 'dd-agent'
  append true
  only_if { File.exist?("/etc/init.d/datadog-agent") }
end
```

So I added the chefspec test for it:

```
it 'modifies docker group' do
    allow(File).to receive(:exist?).with('/etc/init.d/datadog-agent').and_return true     
    expect(chef_run).to modify_group('docker') 
end
```

And we now get 100% touch coverage (which is our goal) but it fails with this error:

```
Failures:

  1) man::install_docker centos 6 modifies docker group
     Failure/Error: expect(chef_run).to modify_group('docker')
     NameError:
       uninitialized constant RSpec::Support::Differ
     # ./spec/install_docker_spec.rb:84:in `block (3 levels) in <top (required)>'

Finished in 4 minutes 9.9 seconds (files took 3.21 seconds to load)
537 examples, 1 failure

Failed examples:
rspec ./spec/install_docker_spec.rb:81 # man::install_docker centos 6 modifies docker group

ChefSpec Coverage report generated...
  Total Resources:   157
  Touched Resources: 157
  Touch Coverage:    100.0%
```

I've looked high and low on the web for answers and have tried a bunch of different syntaxes, but can't seem to figure out where this error is coming from and why.
As best I can see, it seems to be a bug with rspec, but I'm not sure, so here is the debugging info:

```
uname -a
Linux aws-chef-workstation.***** 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

chef -v
Chef Development Kit Version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

rspec -v
3.5.3

gem list | grep rspec
rspec (3.5.0)
rspec-core (3.5.3)
rspec-expectations (3.5.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
serverspec (2.36.1, 2.30.0)
```

Any help would be appreciated. Thanks in advance.

**Comment by burtlo** [comment]
My guess in this situation is that the problem is in stubbing the `allow(File).to receive(:exist?).with('/etc/init.d/datadog-agent').and_return true` statement.

My thought here is to create a helper method that wraps that `File.exist?` method and then stub that new method.

```ruby
# libraries/default.rb

module DataDogHelpers
  def data_dog_agent_file_present?
    File.exist?('/etc/init.d/datadog-agent')
  end
end
```

Here you create a module with the helper method that doe the File check that you are looking to discover.

```ruby
# recipes/default.rb
group 'docker' do
  extend DataDogHelpers
  action :modify
  members 'dd-agent'
  append true
  only_if { data_dog_agent_file_present? }
end
```

Within the resource where this helper is needed you extend the module: `extend DataDogHelpers`. Extending the module ill append the methods defined in the module to this instance of the group resource.

```ruby
# spec/unit/recipes/default_spec.rb

it 'modifies docker group' do
    allow_any_instance_of(Chef::Resource::Group).to receive(:data_dog_agent_file_present?).and_return(true)   
    expect(chef_run).to modify_group('docker') 
end
```

Finally you need to state that if any instance of the Group Resource were to call this helper method that you want to intercept that and return the value you are after for the scenario. This syntax is tricky and it may seem weird to stub any instance of group when you are only augmenting one particular instance of the group resource ... but the reason for that is because you don't know which instance of group. Meaning that you can't find that instance, put this stub in place, before it is being used because of the nature of resources defined in recipes.

I've seen success with this tactic when confront with a `File.exist?` within a resource guard.

I have an example of the module and recipe here: https://github.com/burtlo/guards/blob/master/recipes/default.rb
I have an example of the specification here: https://github.com/burtlo/guards/blob/master/spec/unit/recipes/default_spec.rb

**Comment by lamont-granquist** [comment]
another case that probably just needs:

```ruby
allow(File).to receive(:exist?).and_call_original
expect(file).to receive(:exist?).with('/etc/init.d/datadog-agent').and_return(true)
```

@tas50 another rspec question that isn't really a bug report.

**Comment by jjustice6** [comment]
For anyone googling this and getting this particular GitHub issue:

the problem is that if you have a file mock in your unit test, and you don't first have
`allow(File).to receive(:exist?).and_call_original`
you can't load the library.

If your test passes, you get away with it and you think everything is fine, but if it fails, when it attempts to actually show you the diff between the good and the bad so you can fix your code, you instead wind up with:
```
     NameError:
       uninitialized constant RSpec::Support::Differ
       Did you mean?  RSpec::Support::Differ
                      Diff
```
and that's obviously utterly unhelpful for finding the bug in your code.


@lamont-granquist : IMO this is unintuitive enough that if it _can_ be solved by chefspec code changes (though i'm not sure if that's viable) then it should be. Otherwise, maybe try to trap this _specific+ error and print some sort of detailed explanation that you should have the `.and_call_original` for any File operation you mock or else you risk breaking the stuff that works under-the-hood.
