### ISSUE TITLE
How to check if windows_path was being assigned in chef recipe?

### ISSUE THREAD

**Issue by connorconway** [chefspec/chefspec#893]
I have just started to use ChefSpec and am just investigating exactly what it allows

I have a chef recipe that installs Sublime and adds sublime to the path variable on windows:

`chocolatey_package 'sublimetext3' do 
	action :upgrade
end`

`windows_path node['sublime']['installation_path'] do
  action :add
  only_if { node['platform_family'] == 'windows' }
end`

Is it possible to test such a thing? 

For example, something like:

`it 'adds sublime to the machines path variable' do
       expect(chef_run).to set_windows_path('pathtocheck')
    end`

I can't seem to find any documentation on this, or exactly what ChefSpec allows you to check for.

Thank you

**Comment by coderanger** [comment]
Hi Connor,
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
