### ISSUE TITLE
testing idempotency in custom resources?

### ISSUE THREAD

**Issue by aespinosa** [chefspec/chefspec#904]
I've done something similar using chef-core style plain unit tests.   But I'm wondering if others has some framework to get this done in chefspec.  

I see #340 but was closed since it was only scoped to resources already in core.

**Comment by lamont-granquist** [comment]
all of the discussion in #340 still applies.

if you're just trying to mock out your own load_current_value / load_current_resource check for if your state needs to be updated or not, then you should do that, with plain old rspec stubs (since it would just be plain old ruby code in your action), then validate that the execute resource or whatever winds up getting not_if'd / only_if'd correctly.

if you are trying to step into a service sub-resource, then you're definitely violating the design philosophy of chefspec and need to write a test-kitchen spec.  any problem which winds up with "i'd like to get state out of a chef core resource" means you have a test-kitchen problem and not a chefspec problem.

we are probably going to pull chefspec into core chef so may revisit this as we get more experience with it, but fundamentally its going to be used to test the resource collection of custom resources, with assumptions that the other resources in it will work.   for the existing providers which do not use sub-resources (like service) we wouldn't use chefspec and would use raw rspec.  the point of chefspec is to inspect a constructed resource collection.

**Comment by aespinosa** [comment]
What I wanted to get out of chefspec is the free setup of the dependent libraries through `#setup_run_context` without rewriting what `CookbookCompiler` does in my `spec_helper.rb`.

Here's how I figured it out so far:


```
require 'chefspec'
require 'chefspec/berkshelf'

describe 'my_custom_resource' do

  before do
    run_context
  end

  let(:run_context) do
    ChefSpec::SoloRunner.new(platform: 'ubuntu', version: '14.04')
      .converge('my_cookbook::empty_recipe')
      .run_context
  end

  subject do
    MyCookbook::MyCustomResource.new 'default', run_context
  end

  # do my actual unit tests
  it do
    subject.run_action :nothing
    is_expected.to_not be_updated
  end
end
```

**Comment by aespinosa** [comment]
figured the best way forward is to use chefspec for compiling the custom resource and then resort to plain rspec for testing the actual resource ala chef-core.

**Comment by sheamusburns** [comment]
It do 😵‍💫
