### ISSUE TITLE
Error with openssl_dhparam

### ISSUE THREAD

**Issue by garthreckers** [chefspec/chefspec#907]
Sorry in advance if this is a dumb question. I'm very new to Chef and have had pretty smooth sailing till I started setting up spec tests.

I am using openssl_dhparam to install a dhparam file for nginx. The code is pretty straight forward:

```ruby
openssl_dhparam 'dhparams' do
  path '/path/to/dhparams.pem'
  key_length 4096
end
```

I can run kitchen converge without issue and run kitchen verify and all my integration tests work including the check to see if dhparams is create. The issue is when I run "chef exec rspec" I get the following error:

```Shell
NoMethodError:
       undefined method 'openssl_dhparam' for cookbook: nginx, recipe: default :Chef::Recipe
       Did you mean?  openbsd_package
```

I tried adding openssl as a dependency to my Berksfile, running berks vendor, then changing the cookbook path to the berks-cookbooks directory hoping that that would solve it but that gave the same error. Here is my spec file with the cookbook path config included (but commented)

```ruby
require 'spec_helper'

describe 'nginx::default' do
  let(:chef_run) do
    ChefSpec::SoloRunner.new(
      platform: 'ubuntu',
      version: '16.04',
      # cookbook_path: ["#{Dir.pwd}/berks-cookbooks"]
    ).converge(described_recipe)
  end

  it 'converges successfully' do
    expect(chef_run).not_to raise_error
  end

  it 'installs nginx' do
    expect(chef_run).to install_package('nginx')
  end
end
````

Any ideas? Pulling my hair out over here and anything will help.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
