### ISSUE TITLE
LoadError: cannot load such file -- chefspec

### ISSUE THREAD

**Issue by danielitogomez** [chefspec/chefspec#914]
Hello @here

    Some help, please, I want to execute a PR and I get that error. Any idea please ?

LoadError:
--
 cannot load such file -- chefspec
# ./spec/spec_helper.rb:1:in `<top (required)>'
# ./spec/unit/recipes/vh_spec.rb:1:in `require_relative'
# ./spec/unit/recipes/vh_spec.rb:1:in `<top (required)>'
No examples found.

best regards

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
