### ISSUE TITLE
NoMethodError when custom resources uses a custom resource in another cookbook

### ISSUE THREAD

**Issue by splatteredbits** [chefspec/chefspec#995]
My resource:

```
resource_name :permission

property :principal_name, name_property: true
property :type, [:service_account], required: true

action :grant do
  type = new_resource.type
  name = new_resource.principal_name

  if type == :service_account
    crypto_member name do
      group :crypto_readers
      action :add
    end

    crypto_member name do
      group :pgp_readers
      action :add
    end
  end
end
```

The `crypto_member` is defined in another of our internal cookbooks. When I try to run these tests:

```
require 'spec_helper'

describe 'whs_phm_permission' do
  step_into :permission, :whs_crypto_member
  platform 'windows', '2012r2'

  context 'when granting service account permission' do
    recipe do
      permission 'my group' do
        type :service_account
      end
    end

    it { is_expected.to add_crypto_member('my group').with(group: :crypto_readers) }
    it { is_expected.to add_crypto_member('my group').with(group: :pgp_readers) }
  end
end
```

I get:

```
NoMethodError: undefined method `crypto_member' for #<#<Class:0x0000000009455f98>:0x0000000008587a98>
```

How do I tell ChefSpec about the resource in the other cookbook?

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
